version: "3.9"

services:
    app:
        container_name: osd_finalprojectapi
        image: osd_finalprojectapi
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}" 